plugins {
    id("dev.kikugie.stonecutter") version "0.9"
    alias(libs.plugins.forge.moddev)
}
apply from: rootProject.file('buildscript/runtime.gradle')

def minecraftVersion = project.name.split('-', 2)[0]
var is1_21_11 = sc.eval(minecraftVersion, ">=1.21.11")
var is26_1 = sc.eval(minecraftVersion, ">=26.1")

configurations.configureEach {
    resolutionStrategy {
        force "org.apache.logging.log4j:log4j-api:2.19.0" // Introduced by Forge itself
        force "org.apache.logging.log4j:log4j-core:2.19.0" // Introduced by Forge itself
        force "org.ow2.asm:asm:9.8" // To support java 21
        force "org.ow2.asm:asm-commons:9.8" // To support java 21
    }
}

java {
    var java = JavaVersion.VERSION_21

    toolchain.languageVersion = JavaLanguageVersion.of(java.getMajorVersion())
    targetCompatibility = java
    sourceCompatibility = java
}

sourceSets {
    main {
        java {
            exclude "com/discordsrv/fabric/**"
            exclude "com/discordsrv/neoforge/**"
        }
    }
}

stonecutter {
    replacements.string(!is1_21_11) {
        replace("Identifier", "ResourceLocation")
        replace(".identifier()", ".location()")
        replace("ResourceKey::identifier", "ResourceKey::location")
    }
    replacements.string(is26_1, "textplaceholder") {
        replace("PlaceholderHandler", "eu.pb4.placeholders.api.Placeholder.Handler<ServerPlaceholderContext, String>")
        replace("PlaceholderContext", "ServerPlaceholderContext")
        replace("@Nullable String argument", "String argument")
        replace("ctx.player()", "ctx.serverPlayer()")
    }
}

shadowJar {
    configurations = [project.configurations.shadow]
    mergeServiceFiles()

    archiveFileName = "forge.jarinjar"
}

spotless {
    java {
        if (sc.current.isActive)
            target("src/main/java/")
    }
}

artifacts {
    shadow shadowJar
}

legacyForge {
    version = minecraftVersion + "-" + project.property("deps.forge_version")
}

repositories {
    mavenLocal()
    maven { url = 'https://maven.neoforged.net/releases' }
    maven { url = "https://maven.parchmentmc.org" }
}

dependencies {
    // Mixin Extras
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.4"))

    // API
    annotationProcessor project(':api')
    shadow project(':common:common-api')

    // Common
    shadow project(':common')

    runtimeDownload(libs.adventure.api)

    // DependencyDownload
    compileOnly(libs.dependencydownload.jarinjar.loader)
    compileOnly(libs.dependencydownload.jarinjar.bootstrap)
}
