plugins.apply "dev.kikugie.stonecutter"

stonecutter {
    active file("active-version")

    parameters {
        def (version, loader) = current.project.split('-', 2)
        sc.properties.tags(version, loader)
        constants.match(loader, "fabric", "neoforge")

        def minecraft = sc.properties.get("minecraft.version_range_label").split("-")[0]
        targets["minecraft"] = minecraft

        def fml = sc.properties.getOrNull("deps.neoforge_fml_version")
        if (fml != "[VERSIONED]" && fml != null) {
            targets["fml"] = fml.replace("-SNAPSHOT", "")
        }

        swaps["dependencies_file"] = ("\"dependencies/runtimeDownload-${it.current.version}.txt\";").toString()
    }

}