plugins.apply "dev.kikugie.stonecutter"

stonecutter {
    active file("active-version")

    parameters {
        def (version, loader) = current.project.split('-', 2)
        //properties.tags(version, loader)
        constants.match(loader, "fabric", "neoforge")

        def minecraft = node.project.property("minecraft.version_range_label").split("-")[0]
        dependencies["minecraft"] = minecraft

        // Split from the first dash, so we can support versions like 7.0.0-20260602.190347-6
        def adventure = node.project.property("deps.adventure_platform").split("-")[0]
        dependencies["adventure"] = adventure

        def fml = node.project.property("deps.neoforge_fml_version").replace("-SNAPSHOT", "")
        if (fml != "[VERSIONED]") {
            dependencies["fml"] = fml
        }

        swaps["dependencies_file"] = ("\"dependencies/runtimeDownload-${it.current.version}.txt\";").toString()
    }

}