plugins.apply "dev.kikugie.stonecutter"

stonecutter {
    active file("active-version")

    parameters {
        def (version, loader) = sc.current.project.split('-', 2)
        sc.properties.tags(version, loader)
        constants.match(loader, "fabric", "neoforge")

        def minecraft = sc.properties.get("minecraft.version_range_label").split("-")[0]
        if (minecraft != "[VERSIONED]") {
            targets["minecraft"] = minecraft
        }
    }
}